### PR TITLE
Enable strict mode.

### PR DESCRIPTION
**Pull request by stouf**

### CODE REVIEW

**Comment by stouf** [comment]
Hmmm, this repository isn't versioned... We need https://github.com/coursebase/customreport/pull/210 in before merging this other we will break the tests there.

**Comment by stouf** [comment]
> this repository isn't versioned

Let's do it once this gets merged.
https://github.com/coursebase/eslint-config-coursebase/issues/4

**Comment by frankychung** [comment]
Merged coursebase/customreport#210. Good to merge thsi?

**Comment by stouf** [comment]
Yep! Thanks for the review!

**Pull request merged**
